FROM alpine:latest

ARG DANTE_USER
ARG DANTE_PASSWORD

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    apk add --no-cache dante-server

RUN adduser -D $DANTE_USER && echo "$DANTE_USER:$DANTE_PASSWORD" | chpasswd

ENV CFGFILE=/etc/sockd.conf \
    PIDFILE=/tmp/sockd.pid \
    WORKERS=10

EXPOSE 1080

CMD sockd -f $CFGFILE -p $PIDFILE -N $WORKERS
