version: '3.4'

volumes:
  gyazo-data:
  openvpn-data:
  nginx-proxy-vhost:
  nginx-proxy-html:
  nginx-proxy-dhparam:
  nginx-proxy-certs:

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 4433:443
    restart: always
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - nginx-proxy-html:/usr/share/nginx/html
      - nginx-proxy-dhparam:/etc/nginx/dhparam
      - nginx-proxy-certs:/etc/nginx/certs:ro

  letsencrypt-nginx-proxy-companion:
    container_name: letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - nginx-proxy-html:/usr/share/nginx/html
      - nginx-proxy-certs:/etc/nginx/certs
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy

  www:
    container_name: www
    image: nginx:alpine
    restart: always
    volumes:
      - ./www:/www:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www.conf:/etc/nginx/nginx-www.conf:ro
    environment:
      VIRTUAL_HOST: mydomain.com
      LETSENCRYPT_HOST: mydomain.com
      LETSENCRYPT_EMAIL: myemail@gmail.com

  gyazo:
    container_name: gyazo
    image: nginx:alpine
    restart: always
    volumes:
      - gyazo-data:/www:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www.conf:/etc/nginx/nginx-www.conf:ro
    environment:
      VIRTUAL_HOST: gyazo.mydomain.com
      LETSENCRYPT_HOST: gyazo.mydomain.com
      LETSENCRYPT_EMAIL: myemail@gmail.com

  upload:
    container_name: upload
    build:
      context: .
      dockerfile: Dockerfile-upload
    restart: always
    volumes:
      - gyazo-data:/data
    environment:
      HOST: https://gyazo.mydomain.com
      TOKEN: mytoken
      VIRTUAL_HOST: upload.mydomain.com
      LETSENCRYPT_HOST: upload.mydomain.com
      LETSENCRYPT_EMAIL: myemail@gmail.com

  telegram:
    container_name: telegram
    build:
      context: .
      dockerfile: Dockerfile-telegram
      args:
        HOST: telegram.mydomain.com
        APP_ID: 11111
        APP_HASH: 1234567890
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www.conf:/etc/nginx/nginx-www.conf:ro
      - ./nginx-telegram.conf:/etc/nginx/nginx-telegram.conf:ro
    environment:
      VIRTUAL_HOST: telegram.mydomain.com
      LETSENCRYPT_HOST: telegram.mydomain.com
      LETSENCRYPT_EMAIL: myemail@gmail.com

  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 443:1194/udp
    restart: always
    volumes:
      - openvpn-data:/etc/openvpn

  openvpn-tcp:
    container_name: openvpn-tcp
    image: kylemanna/openvpn:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 443:1194/tcp
    restart: always
    volumes:
      - openvpn-data:/etc/openvpn:ro
    command: ovpn_run --proto tcp --port-share mydomain.com 4433

  dante:
    container_name: dante
    build:
      context: .
      dockerfile: Dockerfile-dante
      args:
        DANTE_USER: myuser
        DANTE_PASSWORD: mypassword
    ports:
      - 8080:1080
    restart: always
    volumes:
      - ./sockd.conf:/etc/sockd.conf:ro
