FROM node:alpine

ARG FILE_FOLDER
ARG IMAGE_FOLDER

RUN mkdir -p $FILE_FOLDER
RUN mkdir -p $IMAGE_FOLDER

RUN npm i pm2 -g

RUN apk update && apk upgrade && apk add --no-cache git

WORKDIR /gyazo
ADD https://api.github.com/repos/zzeneg/node-gyazo-upload/git/refs/heads/master /version.json
RUN git clone https://github.com/zzeneg/node-gyazo-upload.git ./
RUN npm i

EXPOSE 80

CMD ["pm2-runtime", "start", "server.js"]
