FROM node:alpine

WORKDIR /gyazo
ADD https://api.github.com/repos/zzeneg/node-gyazo-upload/git/refs/heads/master /version.json
RUN apk add --no-cache git && \
    git clone https://github.com/zzeneg/node-gyazo-upload.git ./ && \
    npm i

RUN npm i pm2 -g

ENV HOST=localhost \
    PORT=80 \
    URL=/ \
    TOKEN=qwerty123! \
    WEB_SERVER_FOLDER=/data \
    FILE_FOLDER=/ \
    IMAGE_FOLDER=/i

VOLUME $WEB_SERVER_FOLDER

EXPOSE $PORT

CMD mkdir -p $WEB_SERVER_FOLDER/$FILE_FOLDER && mkdir -p $WEB_SERVER_FOLDER/$IMAGE_FOLDER && pm2-runtime server.js
