FROM node:alpine as builder

RUN apk add --no-cache git

WORKDIR /webogram
ADD https://api.github.com/repos/zhukov/webogram/git/refs/heads/master /version.json
RUN git clone https://github.com/zhukov/webogram.git ./ && npm i

# replace web.telegram.org links with proxy
# replace AppId, AppHash and domains
# disable ngAnnotate (requires > 1Gb memory)
RUN sed -i "s|'https://' + subdomain + '.web.telegram.org/'|'https://telegram.mydomain.com/' + subdomain + '/'|g" ./app/js/lib/mtproto.js && \
    sed -i "s|2496|myAppId|g" ./app/js/lib/config.js && \
    sed -i "s|8da85b0d5bfe62527e5b244c209159c3|myAppHash|g" ./app/js/lib/config.js && \
    sed -i "s|'web.telegram.org', 'zhukov.github.io'|'telegram.mydomain.com'|g" ./app/js/lib/config.js && \
    sed -i "s|'concat', $.ngAnnotate(), $.uglify([{]outSourceMap: false[}])|'concat', $.uglify({outSourceMap: false, mangle: false})|g" ./gulpfile.js && \
    npm run clean && \
    npm run build



FROM nginx:alpine

COPY --from=builder /webogram/dist /www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
