version: '3.4'

volumes:
  openvpn-data:
  nginx-proxy-vhost:
  nginx-proxy-html:
  nginx-proxy-dhparam:
  nginx-proxy-certs:

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 4433:443
    restart: always
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - nginx-proxy-html:/usr/share/nginx/html
      - nginx-proxy-dhparam:/etc/nginx/dhparam
      - nginx-proxy-certs:/etc/nginx/certs:ro

  letsencrypt-nginx-proxy-companion:
    container_name: letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - nginx-proxy-html:/usr/share/nginx/html
      - nginx-proxy-certs:/etc/nginx/certs
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy

  www:
    container_name: www
    image: nginx:alpine
    restart: always
    volumes:
      - ./www:/www:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www.conf:/etc/nginx/nginx-www.conf:ro
    environment:
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}

  telegram:
    container_name: telegram
    build:
      context: .
      dockerfile: Dockerfile-telegram
      args:
        HOST: telegram.${HOST}
        APP_ID: ${TELEGRAM_APP_ID}
        APP_HASH: ${TELEGRAM_APP_HASH}
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www.conf:/etc/nginx/nginx-www.conf:ro
      - ./nginx-telegram.conf:/etc/nginx/nginx-telegram.conf:ro
    environment:
      VIRTUAL_HOST: telegram.${HOST}
      LETSENCRYPT_HOST: telegram.${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}

  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 443:1194/udp
    restart: always
    volumes:
      - openvpn-data:/etc/openvpn

  openvpn-tcp:
    container_name: openvpn-tcp
    image: kylemanna/openvpn:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 443:1194/tcp
    restart: always
    volumes:
      - openvpn-data:/etc/openvpn:ro
    command: ovpn_run --proto tcp --port-share ${HOST_IP} 4433

  dante:
    container_name: dante
    build:
      context: .
      dockerfile: Dockerfile-dante
      args:
        DANTE_USER: ${DANTE_USER}
        DANTE_PASSWORD: ${DANTE_PASSWORD}
    ports:
      - 8080:1080
    restart: always
    volumes:
      - ./sockd.conf:/etc/sockd.conf:ro

  ble-light:
    container_name: ble-light
    image: nginx:alpine
    restart: always
    volumes:
      - ./ble-light:/www:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www.conf:/etc/nginx/nginx-www.conf:ro
    environment:
      VIRTUAL_HOST: blelight.${HOST}
      LETSENCRYPT_HOST: blelight.${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}

  calibre:
    container_name: calibre
    image: technosoft2000/calibre-web
    restart: always
    volumes:
      - ./calibre:/books
    environment:
      VIRTUAL_HOST: calibre.${HOST}
      LETSENCRYPT_HOST: calibre.${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}

  smtp:
    container_name: smtp
    image: namshi/smtp
    restart: always
    environment:
      MAILNAME: ${HOST}

  sharex:
    container_name: sharex
    build:
      context: .
      dockerfile: Dockerfile-sharex
    restart: always
    volumes:
      - ./sharex-config.json:/sharex/config.json:ro
      - ./sharex:/sharex/server/uploads
    environment:
      VIRTUAL_HOST: sharex.${HOST}
      LETSENCRYPT_HOST: sharex.${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
