FROM node:alpine

RUN apk add --no-cache git && \
    npm i pm2 -g

WORKDIR /sharex
ADD https://api.github.com/repos/TannerReynolds/node-sharex-server/git/refs/heads/master /version.json
RUN git clone https://github.com/TannerReynolds/node-sharex-server.git ./ && \
    npm i

EXPOSE 80

CMD ["pm2-runtime", "start", "index.js"]
